### ISSUE TITLE
Week 1 Goals

### ISSUE THREAD

**Issue by ashwinc12** [FRCteam4909/2019-Deep-Space#1]
- [ ] Discuss New Branching (Master, Testing, Competition)

- [ ] Discuss Code Structure

- [ ] Complete basic OI / Controllers

**Comment by roshanr10** [comment]
@ashwinc12 my advice would be to split this into multiple issues, this is too broad and has no sense of ownership. you can use GitHub milestones (a feature under the issues tab) to track multiple issues under one goal/deadline
