### ISSUE TITLE
Implement Elevator Height Setpoints

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#154]
This requires some more ingenuity in terms of figuring out the control scheme. What's been talked about is a "shift key" of sorts that will allow us to use the existing four buttons(A,B,X,Y) as eight buttons, mapping to each possible orientation of the hatch and cargo placement.

Done Includes
- [ ] Elevator Commands that PID to a given Encoder Value aka Height Setpoint
- [ ] Implementing a "Shift Key" type of Trigger for the button mapping
- [ ] Discussing with drive team on how the buttons should be configured

Also, before we dive too deep into this, I think we should ask them if they'd use this if available.

**Comment by ashwinc12** [comment]
Talked to Jeff and he seemed content without setpoints as he knew how far to go anyways
