### ISSUE TITLE
Look into Alternate Ways to Mount NavX

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#155]
NavX needs to be on a surface perpendicular to the ground in order to function properly according to the doc.

Done Includes
- [ ] Look into Wiring Options off board the Rio
- [ ] Discuss with Build on Mounting w/ Respect to Potential Wiring

**Comment by derrell** [comment]
Thoughts on this... I see two easy (famous last words) options here: mount the Rio horizontally or vertically; or mount the Navx horizontally or vertically while leaving the Rio where it is. I believe the Rio need not move off of the electronics board in either case. We can build Lexan triangle brackets that level the Rio in its current location; or build similar but smaller brackets that level the Navx horizontally immediately above its current location, with a few-inch piece of ribbon cable to wire it to the Rio.
