### ISSUE TITLE
Driving in straight line using white tape

### ISSUE THREAD

**Issue by ashwinc12** [FRCteam4909/2019-Deep-Space#16]
Continuing the discussion from today's meeting... comment ideas below

**Comment by ashwinc12** [comment]
I found something that could potentially work. Using 6 infrared sensors spread apart evenly at the front of the robot, if the average of the left three sensors is less than the right, than move to the right and vice-versa. Just one option. 

[https://maker.pro/arduino/projects/make-line-follower-robot]

**Comment by TechplexEngineer** [comment]
We have qty (4) of these that should be able to detect the tape on the floor. 
https://www.firstchoicebyandymark.com/fc-42ef-d2mpak-f4

https://www.youtube.com/watch?v=uPFfevfpMxs

**Comment by roshanr10** [comment]
Something to keep in mind about line followers is that a lot of them assume you’re on the line... we should check the tolerances on the sensor and how close the driver has to get it before the sensors can take over.

**Comment by roshanr10** [comment]
> We could use easier forms of blob detection with pre-programmed functions.
@sMyn42 could you clarify what you meant by these “pre-programmed functions”? blob detection for the line using vision?

**Comment by derrell** [comment]
Let's not close issues until they get pulled into master, so we don't forget that they are pending. Reopening.

**Comment by roshanr10** [comment]
closing for now as per prev. comment, please reopen if deemed necessary
