### ISSUE TITLE
Implement Autonomous Climb Functionality

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#163]
Title says it all, attempt to have a one click climb functionality that uses LIDAR and the encoders to climb onto a given HAB level.

Ex. Typical Workflow to L3*
- [ ] Level Bottom Wheels while on L1
- [ ] Lift Robot to L3
- [ ] Drive Forward till X distance from DS Wall
- [ ] Raise Front Stilts / Elevator
- [ ] Drive Forward till Y distance from DS Wall
- [ ] Raise Back Stilts
- [ ] Drive Forward till X distance from DS Wall

* this is assuming the intake has been hooked on, I say we start there and go from that.

**Comment by ashwinc12** [comment]
Doesn't seem like drivers wanted this
