### ISSUE TITLE
Implement Intake Subsystem

### ISSUE THREAD

**Issue by ashwinc12** [FRCteam4909/2019-Deep-Space#33]
- [ ] Intake (Subsystem)
- [ ] Open Hatch Intake (Instant Command)
- [ ] Close Hatch Intake (Instant Command)
- [ ] Run Cargo Intake Inward (Continous Command)
- [ ] Run Cargo Intake Outward (Continous Command)

**Comment by Vultimate1** [comment]
I pushed the code I wrote for the Intake subsystem as a command.  Do you know when the intake subsystem is going to be finished?

**Comment by roshanr10** [comment]
just took a look at the as per the intake subsystem code that Jason was working on, with Flood's new intake design, we only need one SPX(wired via CAN), and all the methods names should be more descriptive with game significance.

Please open a PR to testing when done, thanks!

**Comment by roshanr10** [comment]
I've updated the initial commit message to reflect a checklist of what needs to be implemented for the intake.

**Comment by roshanr10** [comment]
Followed by #38

**Comment by roshanr10** [comment]
Pushed, now being tested as part of #43 - closing issue.
