### ISSUE TITLE
Use Current from PDP to Limit Motor (Intake)

### ISSUE THREAD

**Issue by TechplexEngineer** [FRCteam4909/2019-Deep-Space#38]
Given an intake that uses a motor to manipulate a cargo, we will want code that measures the current drawn by the motor and provide a limit to ensure we don't pop the ball. 

- [ ]  When a "current spike" is detected, slow the motor and or stop the motor.
- [ ] Research code needed to prevent a stalled 775 motor from blowing up in smoke (I believe 195 does this)

**Comment by roshanr10** [comment]
If we’re using SPXs, as previously discussed, they offer their own built in mechanism for current limiting, for both peak and continuous draw.

I’m not sure of the intricacies of this functionality but it may be simpler than running a continuous loop on the Rio checking for current draw.

Just something to consider as we look more into this.

**Comment by roshanr10** [comment]
Disregard my previous comment— I misread the SRX vs SPX disclaimer in the combined manual.

**Comment by TechplexEngineer** [comment]
Using SRX's for this should work shouldn't it. What disclaimer did you read?

**Comment by roshanr10** [comment]
SRXs will, SPXs don’t have the ability, but that’s a $100 difference. It’s mentioned in the documentation in several places, I’ll add a link later.

**Comment by roshanr10** [comment]
https://phoenix-documentation.readthedocs.io/en/latest/ch13_MC.html

it’s mentioned on here, how the method exists but always returns 0 on the SPX.

do we want to consider using SRXs for just this functionality?

**Comment by roshanr10** [comment]
While we plan to have an IR sensor to detect when we are in possession of a ball, I'd like to investigate using current limiting as a secondary failsafe.

**Comment by ashwinc12** [comment]
@roshanr10 What's the status of this?

**Comment by roshanr10** [comment]
Ready for testing on comp bot, it’s been PRed

**Comment by roshanr10** [comment]
this seemingly works, but we have to hone down the exact numbers Monday

**Comment by roshanr10** [comment]
some psuedocode I got from a discussion on a FRC channel:
```current = pdp.getCurrentOnChannel()
signal = 1.0 // your pwm value
if (current > limit)
    signal *= limit/current```

theoretically this'll work more effectively than what we have now, will test tomorrow

**Comment by Vultimate1** [comment]
@roshanr10 I have the current limiting code using the newer IntakeSubsystem and I can PR it, if you want.

**Comment by roshanr10** [comment]
Nah, we’re all set, I pulled in the relevant changes

**Comment by roshanr10** [comment]
closing based on IR sensor success
