### ISSUE TITLE
Add Reusable Code from Last Year

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#4]
- [x] OI
- [ ] LEDs

**Comment by roshanr10** [comment]
do you want LEDs? @ashwinc12

**Comment by ashwinc12** [comment]
Yeah we can add that in later today

**Comment by ashwinc12** [comment]
@roshanr10 Can you add the LED stuff you want to reuse?

**Comment by roshanr10** [comment]
Add in what you wish, it should just be one class

**Comment by ashwinc12** [comment]
I believe we will be scratching the old Arduino code from last year and rewriting it ... Safe to say this issue can be  closed
