### ISSUE TITLE
Test Current Code (IR, LiDAR, LineFollow & Intake in Testing Branch)

### ISSUE THREAD

**Issue by ashwinc12** [FRCteam4909/2019-Deep-Space#43]

**Comment by roshanr10** [comment]
Threading onto the many starting positions, consider using enums to hold on the different aspects of the many states if needed. That way we’re not dealing with multiple Boolean if statements per condition.

**Comment by jasonbishop11** [comment]
- [ ] Test LineFollow Command
- [ ] Test LIDAR
- [ ] Test intake subsystem
- [ ] Attach cameras to chassis
- [ ]Test vision (Maybe?)
- [ ]Compress camera streams using openCV
- [ ] Test Drivetrain switch/invert
