### ISSUE TITLE
Investigate using IR Sensor (Intake)

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#44]
I would like to use the IR sensor for detecting ball possession to avoid running the motors and possibly damaging game pieces. 

See: https://cdn-shop.adafruit.com/product-files/1031/GP2Y0A02YK-DATA-SHEET.PDF

So far, I've gotten a sensor to provide analog values back, we need to be able to translate that into usable values. The primary thought process is that we can use it similar to a garage door tripwire to detect when the voltage changes, we need to experiment with how effective that may be. 

The intake sides are spread apart by 16in.

**Comment by roshanr10** [comment]
See referenced comments in #47

**Comment by roshanr10** [comment]
Also side note, the real intake is 16" wide, while the prototype one is 17", minor details, but just something to remember to recalibrate.

**Comment by ashwinc12** [comment]
Task was completed... now in testing phase in #43
