### ISSUE TITLE
Implement Elevator

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#53]
Hardware:
- [x] 1x SRX Master
- [x]  3x SPX Slave
- [x] 1x SRX Magnetic Encoder

Commands
- [x] Go to Height Setpoint
- [x] Go Speed (-1, 1)

**Comment by TechplexEngineer** [comment]
Do we have 3x spx's ?

**Comment by roshanr10** [comment]
We should have at least 4 SRXs and 4 SPXs (we bought extras since we didn’t
know about the Neos till after) .. I will check the exact count Monday and
post back what I find
