### ISSUE TITLE
Design + Implement User Interface

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#55]
We need to design the user interface based upon the following requirements (embedded below, found [here](https://github.com/FRCteam4909/2019-Deep-Space/wiki/UI-requirements))

#### Driver Controller
- Need Camera to see the floor lines and ahead of me
- A camera to see where the ball is in intake
- Button to switch between manual and auto modes
- Line Tracking auto
- Maybe a slower speed and higher speed button, something that changes the max speed I can hit when pushing the joystick
- Climbing mode button, something to switch between regular elevator operation and a climb mode
- Buttons to control the the elevator side when climbing and the stilts
- Button to switch back to front and vice versa

#### Operator Controller
- Camera or sensor to tell if we control a game piece
- Manual control of the intake 
- Setpoint heights for the rocket, cargo bay, and loading station
- Emergency full manual control of all subsystems
- Display telling me the orientation of the wrist

**Comment by roshanr10** [comment]
Here's what we came up in our discussion for dashboard:

Both Driver/Operator Screens:
- Match Timing
- Cargo Detection (Based on IR Sensors)

Main Screen Only (Jeff & Matt):
- FRC Driver Station
- Both Camera Streams
- Line Alignment (4x Photoelectric Sensors Feedback)
- Elevator Height (encoder ticks, for climbing)
- Drivetrain Inversion

Operator Screen Only (Jeff):
- Semiautonomous Commands Interface
- Elevator Arm Angle
- Intake Motor Current Reading

Test Pane:
- LIDAR Distance
- Intake IR Sensor Values

**Comment by roshanr10** [comment]
Cameras: 
- Facing Intake (Hatch & Cargo)
- Facing Floor Lines
- Facing Ahead

I'm currently unsure if we want ahead & floor lines taken care of by the same camera or have a switching functionality... thoughts?

**Comment by roshanr10** [comment]
Prior to #77, I think we need to finalize both gamepads for their full functionality control. thoughts? @ashwinc12

**Comment by ashwinc12** [comment]
Yes. We should have both gamepads ready for competition in case the smartdashboard stuff doesn't work or if the drivers preferred gamepads instead. 

As of right now,

driverGamepad can do the following

- Drive

- Invert Drive

- Linefollow

manipulatorGamepad can do the following

- Cargo Intake In & Out

-  Hatch Panel Open & Close

- Elevator Up and Down

- Elevator Arm Pivot

**Comment by roshanr10** [comment]
Here's what I'm thinking, feel free to add/change:

Driver Gamepad:
- LY: Drive Speed
- RX: Drive Rotation
- LT: Drive Stilts
- LB: Retract Stilts
- RT: Invert Drive Direction

Operator Gamepad:
- LY: Elevator Arm Pivot
- RY: Elevator Speed
- RT: Cargo Intake In
- RB: Cargo Intake Out
- LT: Hatch Panel Intake In
- Y: Rocket Top Hatch Panel (Elevator Setpoint)
- X: Rocket Medium Hatch Panel (Elevator Setpoint)
- A: Cargo Ship/Human Player/Rocket Low - Hatch Panel (Elevator Setpoint)
- B: Cargo Ship - Cargo (Elevator Setpoint)

I'm aware the manual control doesn't include buttons for Rocket Cargo placement, but I think it's close enough at that point that we can easily manually maneuver it closer within the small gap, and adding other controls would add unneeded complexity given how this is intended to be a fallback. That said, an option would be to have a single button, say `RT` be pressed after choosing the hatch panel setpoint to correct to the cargo setpoint since they all maintain the same offset.

**Comment by roshanr10** [comment]
This is also assuming my comments in #56 that the stilts automatically engage to keep the robot level once the elevator begins to lift the robot off the ground and that once `LB` is pressed, the PID loop is subsequently disabled.

Furthermore, the elevator hatch panel setpoints are intended to set heights and wrist articulation, to clarify.

**Comment by roshanr10** [comment]
cleaned up and revived as #83.

**Comment by derrell** [comment]
Why is this issue closed?

**Comment by derrell** [comment]
It's hard to understand how this could all be determined entirely by the software team. The software team is not doing the driving or operating... And furthermore, it seems like all of the recommendations of the expert in the field of user interface design have been ignored in the process of coming up with these solutions. It's your choice, of course, but seems a poor decision, to me.

The goal of user interface design is to devise the interface that best accomplishes the goal, appropriately divides the operations between the available operators (in this case, the driver and operator), and importantly, makes it least likely that mistakes will be made. There is a very lot that goes into creating a good user interface. I'd highly recommend that you discuss this with me, or even better, Shelley, and that the driver and operator be extensively involved in determining how it will work the best for them. Remember the mantra: You, the software engineer, are NOT the typical user. It's best not to make assumptions based on your own feelings.

**Comment by roshanr10** [comment]
This issue was streamlined in the new issue #83 as per my last comment, all
of the content is otherwise identical, but this was becoming immensely
difficult to follow.

**Comment by roshanr10** [comment]
To clarify, this is not the final revision. We just wanted to make it easier to follow along the design process as it documented in #83. That’s been sent out to Matt & Jeff for a preliminary review, this was just to start discussion.

**Comment by roshanr10** [comment]
Closing as per earlier discussion, this is valuable information but more difficult to see the overall perspective as in #83
