### ISSUE TITLE
Implement Stilts & Climber

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#56]
Hardware (discuss more w/ build on motor controllers, and encoders requirements)
- [ ] 1x Drive Wheels (SPX) (Bag motor)
- [ ] 1x Lift Motor (SRX) (Bag motor) (Encoder)

Commands (works in conjunction w/ existing elevator setpoints)
- [ ] Drive Stilt Wheels Speed
- [ ] Control Stilts Speed (manual power setpoint)

**Comment by roshanr10** [comment]
we're waiting on #63 but theoretically this'll just follow the elevator going up when this is enabled to try to keep the robot level

**Comment by roshanr10** [comment]
i think this should be built as part of the existing elevator subsystem and kick in whenever the elevator subsystem tries to go farther negative (below the initial starting point), and then have a retract upward feature

**Comment by roshanr10** [comment]
one way to to do this would have the stilts PID on gyro values to be level when the stilts are activated– then once you're mostly on, you can override the PID and bring them up as well

**Comment by roshanr10** [comment]
blocked by #63

**Comment by ShashJar** [comment]
See climber branch.

Newest commit saw writing of untested code for stilts in climber subsystem. Included classes are DriveStilts and RetractStilts with buttons specified in #83.

To-Do List for this code for next meeting:

- "The type ClimberSubsystem must implement the inherited abstract method Subsystem.initDefaultCommand()" error showing up on Climber Subsystem class when declared

- Figure out which motor will be used for climber and fill this in in Climber Subsystem class for RobotMap object

- Test code with robot

**Comment by roshanr10** [comment]
For future, WIP branches are nice because it allows for easier code
comments and can eventually be merged in. I’ll take a look in a few hours.

I think I’ve seen the first issue in past, I’ll see what I can do.

**Comment by roshanr10** [comment]
There are two motors within the subsystem on entirely different gearboxes...see initial comment in issue.

**Comment by roshanr10** [comment]
You just need to implement `initDefaultCommand()` as an empty method to avoid throwing the aforementioned error

**Comment by ShashJar** [comment]
To-Do for this Issue as of 02/17:

- Test manual control of climber stilt and climber drive and assign to controls
- Test automatic control of climber stilt in conjunction with elevator
- Fix PID values for elevator arm and climber, and potentially elevator
https://robotics.stackexchange.com/questions/167/what-are-good-strategies-for-tuning-pid-loops
- Consider using an additional manipulator gamepad for climber and elevator if necessary - need to discuss with drive
