### ISSUE TITLE
Reflective Tape Detection with OpenCV

### ISSUE THREAD

**Issue by sMyn42** [FRCteam4909/2019-Deep-Space#66]
Determine whether or not to use the Pi, and figure out what types are retuned by common OpenCV functions in Java.

The end goal is to be able to incorporate error from the angled tape camera into a PID.

**Comment by sMyn42** [comment]
The camera stream issue is done, we have 2 cameras running on decent resolution, and 20 fps.

**Comment by Vultimate1** [comment]
I have code for the GRIP reflective tape detection that returns a value indicating how much the robot should turn to line up with the tape, and follow the line.  I just need to test it tomorrow.

**Comment by derrell** [comment]
Nice work!

**Comment by Vultimate1** [comment]
Anybody know if it is possible to transfer the GRIP program output to the SmartDashBoard to display it?

**Comment by roshanr10** [comment]
You'd have to use CameraServer to push the stream to the robot if I remember correctly, @sMyn42 may have a better idea

**Comment by TechplexEngineer** [comment]
Where do you plan to execute your GRIP pipeline? On the roborio, on a
raspberry pi?

Once you answer that question we can discuss getting the data out of the
pipeline

**Comment by sMyn42** [comment]
We decided to just stick to java and open cv, no Pi.

**Comment by roshanr10** [comment]
@sMyn42 can you work with @Vultimate1 to display on the SmartDashboard during Monday's meeting?

**Comment by Vultimate1** [comment]
Is vision processing still a possibility?  If so, we could just use the grip file created for detecting the reflective tape, without any java code.  We can still see the reflective tape through the grip file.  I've made it so you see its outlined shape to detect the tape.

**Comment by roshanr10** [comment]
@Vultimate1 if you can get working *offboard*, then we can consider it. can you provide a more in depth explanation of your proposal?

**Comment by roshanr10** [comment]
decided against.
