### ISSUE TITLE
Setup Spark MAX and NEO motors for testing

### ISSUE THREAD

**Issue by TechplexEngineer** [FRCteam4909/2019-Deep-Space#7]
We currently have two NEO brushless DC motors, and two Spark MAX motor controllers to control them.

We should learn about the new features of the MAX controllers and develop test code for both PWM and CAN operation.

**Comment by ashwinc12** [comment]
Both SPARK MAX's were updated with the new firmware last meeting

**Comment by roshanr10** [comment]
I'd like someone to follow up with the API releases through forums/support because it seems as though they have yet to release an API publicly for Java/CPP

**Comment by TechplexEngineer** [comment]
Two more are ordered and on the way

**Comment by roshanr10** [comment]
> Two more are ordered and on the way

Sounds good, so we're looking at a total of four sets of Neos/Maxes?

**Comment by TechplexEngineer** [comment]
yup
