### ISSUE TITLE
Investigate Uses of LIDAR

### ISSUE THREAD

**Issue by ShashJar** [FRCteam4909/2019-Deep-Space#71]
Direct LIDAR-to-Rio communication has been successful thus far. After some further testing, it is necessary to start implementing LIDAR into field actions. Current (as of 02/06/19) ideas include:
- Implementing in conjunction with Line Follow so that we position the robot a certain distance from the ship/bay and then move into an intake or outtake command
- Detecting distance from wall when climbing, coordinating with climbing subsystem
- Ensuring perfect or close-to-perfect alignment with rocket ship when elevator is rising to meet middle or top bay

**Comment by roshanr10** [comment]
@ashwinc12 is this in testing?

**Comment by ashwinc12** [comment]
Lidar is only used with Linefollow at the moment which is in testing
