### ISSUE TITLE
Test NavX Gyro 

### ISSUE THREAD

**Issue by ashwinc12** [FRCteam4909/2019-Deep-Space#74]
-Use gyro to align with stilts

**Comment by roshanr10** [comment]
Potential duplicate of #63? Also, the NavX is not guaranteed to work in it's current orientation, just something to think about. That said, I think it's a standard PATA/IDE connection you'll find standard in any desktop pre-2006, so we might be able to salvage a ribbon cable to mount it elsewhere. Or, we could test the USB connection– just something to think about
