### ISSUE TITLE
Needs to be tested

### ISSUE THREAD

**Issue by ashwinc12** [FRCteam4909/2019-Deep-Space#76]
Running list of things that need to be tested on competition bot; feel free to add things to list

-Switch drive
-Line follow with an angled orientation
-Cargo intake commands (in, out, hold)
-Hatch panel intake commands (open, close)

**Comment by derrell** [comment]
- Each low-level Command should be individually tested
- Each higher-level CommandGroup should be tested
- Manual control of each actuator (via, eventually, the secondary gamepad)

**Comment by roshanr10** [comment]
Switch drive had been tested on comp bot, just an FYI

**Comment by ashwinc12** [comment]
**Test Plan**


- [ ] Hatch Panel Open and Close (LB  & RB)

- [ ] Cargo Intake  (X & Y)

- [ ] Elevator Up and Down

- [ ] Elevator SetPoints

- [ ] Test NavX to see what values the `getPivot()` method prints in order to see if it is useable in current position

**Comment by roshanr10** [comment]
@ashwinc12 what does "* Attach Photoelectric sensors in middle to LineFollow" mean?

**Comment by roshanr10** [comment]
closing and breaking down into discrete issues.
