### ISSUE TITLE
Display Robot Camera Feeds

### ISSUE THREAD

**Issue by TechplexEngineer** [FRCteam4909/2019-Deep-Space#8]
Retrieve Robot camera video via the CameraServer, and display it on the laptop screen. This will be a crucial capability this year, so let's learn all about the various capabilities we might have with it. (via Derrell)

- [ ] Figure out how to measure bandwidth used
- [ ] Measure Bandwidth with no camera feed while driving
- [ ] Measure Bandwidth with one feed running
- [ ] Investigate ways to minimize bandwidth used. (Built in options and external options)

**Comment by roshanr10** [comment]
we might have to look more into compression this year with the 4mb limit

**Comment by roshanr10** [comment]
closing as per discussion at meeting
