### ISSUE TITLE
Implement Elevator and Arm PID Loop

### ISSUE THREAD

**Issue by ashwinc12** [FRCteam4909/2019-Deep-Space#82]

**Comment by roshanr10** [comment]
also is there elevator arm using absolute or continuous encoders in the VP right now?

**Comment by roshanr10** [comment]
right now, the PID is not even initialized, see CTRE doc, this is fairly straightforward, and I think a P heavy loop itself would do a majority of the hold position, maybe some D to dampen it– this goes for both arm and elevator

**Comment by roshanr10** [comment]
@jasonbishop11 I'd like this done and tested by end of meeting Monday, if possible. should be just a few lines to get this going, you had most of the basics already implemented if I'm right.

**Comment by roshanr10** [comment]
Tested and working — closing
