### ISSUE TITLE
Create Elevator & Arm Commands

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#84]
We should have elevator commands so that we can use them as building blocks within our semiauto code, this entails making the requisite commands, and instantiating the proper default command.

**Comment by roshanr10** [comment]
@jasonbishop11 I'd also like this done and tested by end of meeting Monday, if possible. this is a little more substantial than #82 but shouldn't be too difficult in my opinion.

give it a go, and let me know if you have any questions

**Comment by roshanr10** [comment]
Need to find set points for this

**Comment by ashwinc12** [comment]
These are coming in with the new pull request

**Comment by roshanr10** [comment]
which PR, use tags

**Comment by roshanr10** [comment]
continued in #88, closing
