### ISSUE TITLE
Develop WPI SmartDashboard UI

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#90]
This issue entails taking #89 and putting together a minimum viable interface in the event we do not have a custom dashboard or if other problems arise.

The layout should be saved & committed to version history.

**Comment by ashwinc12** [comment]
Status?

**Comment by roshanr10** [comment]
As far as I’m aware, not much change formally, maybe done camera streams
and debug values

**Comment by roshanr10** [comment]
while current plan is to do #91, I think this should be done as a failsafe. if we do it right, it should take less than 30 minutes as it uses the same values as the custom dashboard would– this way we have a reliable backup in the event we need it

**Comment by roshanr10** [comment]
has been done, works currently.
