### ISSUE TITLE
Develop Custom HTML Dashboard

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/2019-Deep-Space#91]
Once #89 & #90 are complete, I'd like to put together a more user-friendly dashboard in Bootstrap... I've put together most of this in my spare time already, I just need to make modifications as per the outputs in #89.

**Comment by ashwinc12** [comment]
Status?

**Comment by roshanr10** [comment]
Was this decided against? I have base code for this if you want... how’s
touchscreen interface going?

**Comment by roshanr10** [comment]
![IMG_1581](https://user-images.githubusercontent.com/4524103/54308522-90ee4c00-45a4-11e9-8150-6cc96f09ce9c.jpeg)
![IMG_1582](https://user-images.githubusercontent.com/4524103/54308527-92b80f80-45a4-11e9-8de2-58c69b10a95e.jpeg)
