### ISSUE TITLE
Map Gamepad Buttons for both controllers

### ISSUE THREAD

**Issue by ashwinc12** [FRCteam4909/2019-Deep-Space#92]
- I know that the plan is to implement a user interface but I'd like to have the gamepads ready anyways

**Comment by roshanr10** [comment]
The reasoning behind this is to cover edge cases if the touch screen fails-
we currently have no backup in that case.

Given what we have right now, and based on discussion yesterday, I think we
should be ABLE to fallback to any other team laptop and still be able to
compete successfully, while losing the semiautos... ideally, all else
should remain constant for the drivers.

Semi-autos are nice but robustness is also important, and gamepad are
rather easy to check off as a fallback on the way.

**Comment by ashwinc12** [comment]
This seems to be done

**Comment by roshanr10** [comment]
“Seems to be”?

**Comment by roshanr10** [comment]
![57361426509__EA7C778D-2552-430F-9586-F5BD84AC3BF9](https://user-images.githubusercontent.com/4524103/54308528-9350a600-45a4-11e9-9114-10966201dd1f.jpeg)
![57361427846__F946DEC8-B26B-417E-B420-756B889AF850](https://user-images.githubusercontent.com/4524103/54308535-951a6980-45a4-11e9-8e62-236b63c67a03.jpeg)
![57361428646__E1A1A8D5-45C8-49B8-9CC1-F7D67B5AD010](https://user-images.githubusercontent.com/4524103/54308543-977cc380-45a4-11e9-94f8-f11d3c3b0933.jpeg)
